### ISSUE TITLE
The configuration example to add an extra element doesn't work.

### ISSUE THREAD

**Issue by wimstefan** [aperezdc/vim-lining#1]
Using the example with the pencil color scheme gives that error:

``` viml
Plug 'aperezdc/vim-lining'
call lining#left("%{empty(PencilMode()) ? 'none' : PencilMode()}", 'Item')
```

``` viml
E117: Unknown function: lining#left
```

**Comment by aperezdc** [comment]
I see that you are using [vim-plug](https://github.com/junegunn/vim-plug) for managing Vim plugins (that's cool, I do myself!), so you need to call `plug#end()` _before_ you can use functions defined by plugins. Try editing your `~/.vimrc` so it has something like this:

``` vim
call plug#begin()
Plug 'aperezdc/vim-lining'
call plug#end()

call lining#left('Potato')
```

That should work, and an item with the text `Potato` in it should appear after closing and re-opening Vim. If that works, then try changing it to the following snippet to have the Pencil mode (as in the example):

``` vim
call plug#begin()
Plug 'aperezdc/vim-lining'
Plug 'reedes/vim-pencil'
call plug#end()

call lining#left('%{empty(PencilMode()) ? 'none' : PencilMode()}')
```

Note that you can omit the second parameter to `lining#left()`, and in that case it is the same as passing `'Item'` :wink: 

Please comment and reopen this issue if things still don't work after trying these suggestions.

Thanks for your interest in my humble Vim plugin!

**Comment by wimstefan** [comment]
Thanks for the solution! It works now :)
I thought I tried also to place the call outside the plug() function but obviously something went wrong ;-) Anyway it's all good now. B-)

And I really like your plugin! It's a great inspiration for working on my own statusline to understand what I'm doing.

**Comment by aperezdc** [comment]
Great to know that things work now for you!

By the way, if there is some feature that you think `vim-lining` should have, just let me know — like you did with issue #2 (I will be looking into it when I have some time to spare).
