### ISSUE TITLE
Support vim-signify for getting git hunks

### ISSUE THREAD

**Issue by wimstefan** [aperezdc/vim-lining#2]
Well the title says it all. Until now only airblade/vim-gutter is supported ...

**Comment by wimstefan** [comment]
I got it working with adding those lines at line 186 in autoload/lining.vim

``` viml
elseif exists('g:signify_locked')
  function s:git_get_hunks()
    let [hadd, hmod, hdel] = sy#repo#get_stats()
    let hunks = ''
    if hmod > 0
      let hunks = printf(' ~%i', hmod)
    endif
    if hadd > 0
      let hunks = printf('%s +%i', hunks, hadd)
    endif
    if hdel > 0
      let hunks = printf('%s -%i', hunks, hdel)
    endif
    return hunks
  endfunction 
```

There might be better solutions though ... ;-)

**Comment by wimstefan** [comment]
Yes there is .... ;-)

``` viml
elseif exists('g:loaded_signify')
```

**Comment by aperezdc** [comment]
Cool! It is such a small change that I have decided to push it to the repository (commit: 210f27083978a466007e92d4d87cc590c718f6a9). I have credited you as author in the commit. Thanks a lot for figuring this one out :+1:

**Comment by wimstefan** [comment]
Oh sweet! Thanks for the credits :+1: :blush: :sunglasses:

**Comment by wimstefan** [comment]
Ohhh I realize that I didn't give the second (and more elegant) solution for checking if Signify is loaded :flushed: 

``` viml
elseif exists('g:loaded_signify')
```

Sorry about that :confused:

**Comment by aperezdc** [comment]
@wimstefan: I have commited your last suggestion for detecting Signify. Thanks!
